language: clojure

addons:
  chrome: stable

install:
  - lein cljsbuild once test
  - npm install

# not useful
# cache:
#   directories:
#     - node_modules
#     - $HOME/.m2

script:
  - $(npm bin)/karma start
