sudo: required

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose run app lein cljsbuild once test
  - docker-compose run app npm install

  - export

script:
  - docker-compose run app karma start
