version: '3'

services:
  app:
    build: .
    working_dir: /usr/src/app
    command: lein repl :headless :host "0.0.0.0" :port 40000
    ports:
      - "40000:40000"
      - "40001:40001"
    volumes:
      - repository:/usr/src/repository
      - .:/usr/src/app
volumes:
  repository:
