version: '3'

services:
  app:
    build: .
    working_dir: /usr/src/app
    command: >-
      boot
      -d cider/cider-nrepl:0.15.0-SNAPSHOT
      -d refactor-nrepl:2.3.0-SNAPSHOT
      -i "(require 'cider.tasks)"
      cider.tasks/add-middleware -m cider.nrepl/cider-middleware
      cider.tasks/add-middleware -m refactor-nrepl.middleware/wrap-refactor
      wait
      repl -s -p 40000 -b 0.0.0.0
    environment:
      - BOOT_LOCAL_REPO=/usr/src/boot_repository
    ports:
      - "40000:40000"
    volumes:
      - boot_repository:/usr/src/boot_repository
      - .:/usr/src/app
volumes:
  boot_repository:
